language: java
os: linux
dist: trusty
jdk: oraclejdk8
install: true
sudo: false
script: mvn clean install cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.m2